config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users, skip: :invitations

  devise_scope :user do
    # Disable every invitation routes except "/accept", we're managing these in the API
    get 'users/invitations/accept', to: 'devise/invitations#edit', as: :accept_user_invitation
    put 'users/invitations', to: 'devise/invitations#update', as: :user_invitation
  end

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/app/*path', to: 'app#app'
  get '/shared/maps/:map_id', to: 'app#shared', as: :shared_map
  get '/changelog', to: 'app#changelog'

  # Tools
  get '/tools', to: 'tools#index'
  get '/tools/soil-analysis', to: 'tools#soil_analysis'

  resources :links, except: [:show]

  namespace :api do
    api_routes_exceptions = [:new, :edit]
    no_index_api_routes_exceptions = [:index, :new, :edit]

    with_options except: api_routes_exceptions do |api_route|
      # Community-related endpoints
      api_route.resources :families
      api_route.resources :genera
      api_route.resources :resource_interactions
      api_route.resources :resource_interactions_groups
      api_route.resources :resource_notes, except: [:index]
      api_route.resources :resources do
        api_route.resources :resource_notes, only: [:index], path: 'notes'
      end

      # User-related endpoints
      api_route.resource :account, only: [:show, :update]

      # Map-related endpoint, for updates and display
      api_route.resources :activities, only: [:show]
      api_route.resources :elements, except: no_index_api_routes_exceptions do
        api_route.resources :harvests, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
        member do
          post '/duplicate', to: 'elements#duplicate'
        end
      end
      api_route.resources :harvests, except: no_index_api_routes_exceptions
      api_route.resources :layers, except: no_index_api_routes_exceptions
      api_route.resources :notifications, only: [:index, :show, :destroy] do
        collection do
          patch '/archive_all', to: 'notifications#archive_all', as: :archive_all
          delete '/destroy_all_archived', to: 'notifications#destroy_all_archived', as: :destroy_all_archived
        end
        patch '/archive', to: 'notifications#archive', on: :member, as: :archive
      end
      api_route.resources :observations, except: no_index_api_routes_exceptions do
        get '/pictures/:picture_id', to: 'observations#picture', on: :member, as: :picture
        get '/pictures/:picture_id/thumbnail', to: 'observations#picture_thumbnail', on: :member, as: :picture_thumbnail
      end
      api_route.resources :patches, except: no_index_api_routes_exceptions do
        api_route.resources :elements, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :paths, except: no_index_api_routes_exceptions do
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :tasks, except: no_index_api_routes_exceptions
      api_route.resources :team_mates, only: [:create, :show] do
        member do
          patch '/accept', to: 'team_mates#accept'
          delete '/refuse', to: 'team_mates#refuse'
          delete '/leave', to: 'team_mates#leave'
          delete '/remove', to: 'team_mates#remove'
        end
      end
      api_route.resources :users, only: [:show] do
        collection do
          post '/search', to: 'users#search'
          post '/invite', to: 'users#invite'
        end
        post '/resend_invitation', to: 'users#resend_invitation', on: :member
      end

      # Maps and their own data, for listings
      api_route.resources :maps do
        get :picture, on: :member
        # Observations directly linked to the map
        api_route.resources :observations, only: [:index]
        api_route.resources :elements, only: [:index]
        api_route.resources :layers, only: [:index]
        api_route.resources :patches, only: [:index]
        api_route.resources :paths, only: [:index]
        api_route.resources :tasks, only: [:index] do
          get '/names', to: 'tasks#names', on: :collection
        end
        api_route.resources :team_mates, only: [:index]
        # Activities for anything linked to the map
        get '/all_activities', to: 'activities#index', as: :all_activities
        # Harvests for anything linked to the map
        get '/all_harvests', to: 'harvests#all_for_map', as: :all_harvests
        # Observations for anything linked to the map
        get '/all_observations', to: 'observations#all_for_map', as: :all_observations
        # Tasks for anything linked to the map
        get '/all_tasks', to: 'tasks#all_for_map', as: :all_tasks
      end
      get 'shared/maps/:id', to: 'maps#shared', as: :shared_map
    end
  end

  namespace :admin do
    resources :families, concerns: :paginatable
    resources :genera, concerns: :paginatable
    resources :resource_interactions_groups, concerns: :paginatable
    resources :resource_interactions, concerns: :paginatable
    resources :resource_notes, only: [:destroy]
    resources :resources, concerns: :paginatable
    resources :links, except: [:show] do
      put :approve, on: :member
    end
    resources :tags, except: [:new] do
      collection do
        post :batch_process
      end
    end

    get '/import', to: 'import#index'
    get '/import/differences', to: 'import#differences'
    get '/import/library_names', to: 'import#library_names'

    %w[family genus resource resource_interactions_group resource_interaction].each do |r|
      post "/import/#{r}", controller: :import, action: r
      put "/import/#{r}", controller: :import, action: r
    end
  end
end

app/controllers/admin/genera_controller.rb
module Admin
  class GeneraController < AdminApplicationController
    before_action :set_genus, only: [:show, :edit, :update, :destroy]

    # GET /admin/genera
    def index
      @genera = policy_scope(Genus)

      @genera = filter @genera

      @genera = search_order_and_paginate @genera, search_fields: ['name'], allowed_sort_fields: ['genera.name'], default_sort_field: 'genera.name', default_sort_dir: 'asc'
    end

    # GET /admin/genera/1
    def show; end

    # GET /admin/genera/new
    def new
      authorize Genus

      @genus = Genus.new
    end

    # GET /admin/genera/1/edit
    def edit; end

    # POST /admin/genera
    def create
      authorize Genus

      @genus = Genus.new(genus_params)

      if @genus.save
        redirect_to admin_genus_path(@genus), notice: I18n.t('admin.genera.create.success')
      else
        render :new
      end
    end

    # PATCH/PUT /admin/genera/1
    def update
      if @genus.update(genus_params)
        redirect_to admin_genus_path(@genus), notice: I18n.t('admin.genera.update.success')
      else
        render :edit
      end
    end

    # DELETE /admin/genera/1
    def destroy
      @genus.destroy
      redirect_to admin_genera_url, notice: I18n.t('admin.genera.destroy.success')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_genus
      @genus = Genus.find(params[:id])

      authorize @genus
    end

    # Only pick allowed parameters from request
    def genus_params
      params.require(:genus).permit(:name, :description, :source, :family_id, :sync_id)
    end

    def filter(query)
      case params[:source]
      when 'with'
        query = query.where.not(source: '')
      when 'without'
        query = query.where(source: '')
      end

      case params[:resources]
      when 'without'
        query = query.where.missing(:resources)
      end

      query
    end
  end
end

app/controllers/api/genera_controller.rb
module Api
  class GeneraController < ApiApplicationController
    before_action :set_genus, only: [:show, :update, :destroy]

    # GET /genera
    def index
      @genera = policy_scope Genus

      render 'api/genera/index'
    end

    # GET /genera/1
    def show
      render 'api/genera/show'
    end

    # POST /genera
    def create
      authorize Genus
      @genus = Genus.new(genus_params)

      if @genus.save
        render 'api/genera/show', status: :created, location: api_genus_url(@genus)
      else
        render json: @genus.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /genera/1
    def update
      if @genus.update(genus_params)
        render 'api/genera/show', status: :ok, location: api_genus_url(@genus)
      else
        render json: @genus.errors, status: :unprocessable_entity
      end
    end

    # DELETE /genera/1
    def destroy
      @genus.destroy
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_genus
      @genus = Genus.find(params[:id])

      authorize @genus
    end

    # Only pick allowed parameters from request
    def genus_params
      base_params = :name, :description, :source, :family_id
      base_params.push :sync_id if current_user&.admin?

      params.require(:genus).permit(base_params)
    end
  end
end

app/views/admin/genera/_form.html.haml
- url = genus.id ? admin_genus_path : admin_genera_path
= form_for genus, url: url do |f|
  - if genus.errors.any?
    .gp-alert.gp-alert--danger
      %p= t('.errors', count: genus.errors.count)
      %ul
        - genus.errors.full_messages.each do |message|
          %li= message

  ._show-page
    %section._show-page__panel
      .gp-field
        = f.label :name
        = f.text_field :name, required: true
      .gp-field
        = f.label :family_id, t('activerecord.attributes.genus.family')
        = f.collection_select :family_id,
                              Family.all.order(:name),
                              :id,
                              :name,
                              { include_blank: true },
                              { required: true }
      .gp-field
        = f.label :source
        = f.url_field :source

  .gp-actions.gp-actions--bottom
    = f.submit t('generic.save'), class: 'gp-button gp-button--recording'

app/views/admin/genera/edit.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), :admin_genera, role: 'button', class: 'gp-button'
  = link_to t('generic.show'), admin_genus_path(@genus), role: 'button', class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_genus_path(@genus),
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'

= render 'form', genus: @genus

app/views/admin/genera/index.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('.new'), new_admin_genus_path, role: 'button', class: 'gp-button gp-button--creative'

- if @genera.size.positive?
  = render 'admin/widgets/pagination', list: @genera

._filters
  ._filters__section
    ._filters__section__title= t('activerecord.attributes.genus.source')
    = filter_by_link t('generic.all'), filters: { source: nil }, keep: [:search, :resources]
    = filter_by_link t('generic.with'), filters: { source: 'with' }, keep: [:search, :resources]
    = filter_by_link t('generic.without'), filters: { source: 'without' }, keep: [:search, :resources]
  ._filters__section
    ._filters__section__title= t('activerecord.models.resource', count: 2)
    = filter_by_link t('generic.all'), filters: { resources: nil }, keep: [:search, :source]
    = filter_by_link t('generic.without'), filters: { resources: 'without' }, keep: [:search, :source]
  ._filters__spring
  ._filters__section= render 'admin/widgets/search', keep: [:source, :resources]

- if @genera.empty?
  .gp-empty= t('.no_content')
- else
  %table
    %caption.-sr-only= t('.table_caption')
    %thead
      %tr
        %th.-monospace.-right{ scope: 'col' }= t('generic.id')
        %th.-monospace.-right{ scope: 'col' }= t('activerecord.attributes.genus.sync_id')
        %th{ scope: 'col' }= order_by_link t('activerecord.attributes.genus.name'),
                                            'families.name',
                                            keep_filters: [:search, :source, :resources]
        %th{ scope: 'col' }= t('activerecord.attributes.genus.family')
        %th{ scope: 'col' }= t('activerecord.attributes.genus.source')
        %th{ scope: 'col' }= t('activerecord.models.resource', count: 2)
        %th{ scope: 'col' }

    %tbody
      - @genera.each do |genus|
        %tr
          %td.-monospace.-right= genus.id
          %td.-monospace.-right= genus.sync_id.presence || '-'
          %td= link_to genus.name, admin_genus_path(genus)
          = missing_data_element :td, genus.family&.name, replacement: '-'
          %td.centered{ class: (genus.source.present? ? '' : 'warning') }
            = yes_no genus.source.present?
          %td.centered= genus.resources.size
          %td.-actions
            = link_to t('generic.edit'),
                      edit_admin_genus_path(genus),
                      role: 'button',
                      class: 'gp-button gp-button--small'
            = link_to t('generic.destroy'),
                      admin_genus_path(genus),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'gp-button gp-button--small gp-button--destructive'

  = render 'admin/widgets/pagination', list: @genera, name: 'genus'

app/views/admin/genera/new.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_genera_path, role: 'button', class: 'gp-button'

= render 'form', genus: @genus

app/views/admin/genera/show.html.haml
- @page_title = t('.title', name: @genus.name)

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_genera_path, role: 'button', class: 'gp-button'
  = link_to t('generic.edit'), edit_admin_genus_path(@genus), role: 'button', class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_genus_path,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'
._show-page
  %aside._show-page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('generic.id'))
        %dd.-monospace= @genus.id

        %dt= t('generic.definition', value: t('activerecord.attributes.genus.name'))
        %dd= @genus.name

        %dt= t('generic.definition', value: t('activerecord.attributes.genus.sync_id'))
        %dd= @genus.sync_id.presence || '-'

        %dt= t('generic.definition', value: t('activerecord.attributes.genus.family'))
        = missing_data_element :dd, @genus.family, url: edit_admin_genus_url(@genus) do
          - link_to @genus.family.name, admin_family_path(@genus.family)

        %dt= t('generic.definition', value: t('activerecord.attributes.genus.source'))
        = missing_data_element :dd, @genus.source, url: edit_admin_genus_path(@genus) do
          - link_to @genus.source, @genus.source

  ._show-page__content.-grid--2.-grid-gap
    %section
      %h2= t('.resources')
      - if @genus.resources.empty?
        .gp-empty= t('generic.nothing_to_display_yet')
      - else
        %table
          %thead
            %tr
              %th= t('activerecord.attributes.resource.name')
              %th= t('activerecord.attributes.resource.latin_name')
              %th
          %tbody
            - @genus.resources.each do |resource|
              %tr
                %td= link_to resource.name, admin_resource_url(resource)
                = missing_data_element :td, resource.latin_name, replacement: '-'
                %td.-actions
                  = link_to t('generic.edit'),
                            edit_admin_resource_path(resource),
                            role: 'button',
                            class: 'gp-button'
                  = link_to t('generic.destroy'),
                            admin_resource_path(resource),
                            method: :delete,
                            data: { confirm: t('generic.are_you_sure') },
                            role: 'button',
                            class: 'gp-button gp-button--destructive'
      .gp-actions
        = link_to t('.new_resource'),
                  new_admin_resource_path(params: { genus_id: @genus.id }),
                  class: 'gp-button gp-button--creative'

    %section= render 'admin/versions/versions', entity: @genus