config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users, skip: :invitations

  devise_scope :user do
    # Disable every invitation routes except "/accept", we're managing these in the API
    get 'users/invitations/accept', to: 'devise/invitations#edit', as: :accept_user_invitation
    put 'users/invitations', to: 'devise/invitations#update', as: :user_invitation
  end

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/app/*path', to: 'app#app'
  get '/shared/maps/:map_id', to: 'app#shared', as: :shared_map
  get '/changelog', to: 'app#changelog'

  # Tools
  get '/tools', to: 'tools#index'
  get '/tools/soil-analysis', to: 'tools#soil_analysis'

  resources :links, except: [:show]

  namespace :api do
    api_routes_exceptions = [:new, :edit]
    no_index_api_routes_exceptions = [:index, :new, :edit]

    with_options except: api_routes_exceptions do |api_route|
      # Community-related endpoints
      api_route.resources :families
      api_route.resources :genera
      api_route.resources :resource_interactions
      api_route.resources :resource_interactions_groups
      api_route.resources :resource_notes, except: [:index]
      api_route.resources :resources do
        api_route.resources :resource_notes, only: [:index], path: 'notes'
      end

      # User-related endpoints
      api_route.resource :account, only: [:show, :update]

      # Map-related endpoint, for updates and display
      api_route.resources :activities, only: [:show]
      api_route.resources :elements, except: no_index_api_routes_exceptions do
        api_route.resources :harvests, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
        member do
          post '/duplicate', to: 'elements#duplicate'
        end
      end
      api_route.resources :harvests, except: no_index_api_routes_exceptions
      api_route.resources :layers, except: no_index_api_routes_exceptions
      api_route.resources :notifications, only: [:index, :show, :destroy] do
        collection do
          patch '/archive_all', to: 'notifications#archive_all', as: :archive_all
          delete '/destroy_all_archived', to: 'notifications#destroy_all_archived', as: :destroy_all_archived
        end
        patch '/archive', to: 'notifications#archive', on: :member, as: :archive
      end
      api_route.resources :observations, except: no_index_api_routes_exceptions do
        get '/pictures/:picture_id', to: 'observations#picture', on: :member, as: :picture
        get '/pictures/:picture_id/thumbnail', to: 'observations#picture_thumbnail', on: :member, as: :picture_thumbnail
      end
      api_route.resources :patches, except: no_index_api_routes_exceptions do
        api_route.resources :elements, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :paths, except: no_index_api_routes_exceptions do
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :tasks, except: no_index_api_routes_exceptions
      api_route.resources :team_mates, only: [:create, :show] do
        member do
          patch '/accept', to: 'team_mates#accept'
          delete '/refuse', to: 'team_mates#refuse'
          delete '/leave', to: 'team_mates#leave'
          delete '/remove', to: 'team_mates#remove'
        end
      end
      api_route.resources :users, only: [:show] do
        collection do
          post '/search', to: 'users#search'
          post '/invite', to: 'users#invite'
        end
        post '/resend_invitation', to: 'users#resend_invitation', on: :member
      end

      # Maps and their own data, for listings
      api_route.resources :maps do
        get :picture, on: :member
        # Observations directly linked to the map
        api_route.resources :observations, only: [:index]
        api_route.resources :elements, only: [:index]
        api_route.resources :layers, only: [:index]
        api_route.resources :patches, only: [:index]
        api_route.resources :paths, only: [:index]
        api_route.resources :tasks, only: [:index] do
          get '/names', to: 'tasks#names', on: :collection
        end
        api_route.resources :team_mates, only: [:index]
        # Activities for anything linked to the map
        get '/all_activities', to: 'activities#index', as: :all_activities
        # Harvests for anything linked to the map
        get '/all_harvests', to: 'harvests#all_for_map', as: :all_harvests
        # Observations for anything linked to the map
        get '/all_observations', to: 'observations#all_for_map', as: :all_observations
        # Tasks for anything linked to the map
        get '/all_tasks', to: 'tasks#all_for_map', as: :all_tasks
      end
      get 'shared/maps/:id', to: 'maps#shared', as: :shared_map
    end
  end

  namespace :admin do
    resources :families, concerns: :paginatable
    resources :genera, concerns: :paginatable
    resources :resource_interactions_groups, concerns: :paginatable
    resources :resource_interactions, concerns: :paginatable
    resources :resource_notes, only: [:destroy]
    resources :resources, concerns: :paginatable
    resources :links, except: [:show] do
      put :approve, on: :member
    end
    resources :tags, except: [:new] do
      collection do
        post :batch_process
      end
    end

    get '/import', to: 'import#index'
    get '/import/differences', to: 'import#differences'
    get '/import/library_names', to: 'import#library_names'

    %w[family genus resource resource_interactions_group resource_interaction].each do |r|
      post "/import/#{r}", controller: :import, action: r
      put "/import/#{r}", controller: :import, action: r
    end
  end
end

app/models/family.rb
class Family < ApplicationRecord
  enum kingdom: { plant: 0, animal: 1 }

  validates :name, presence: true, uniqueness: true
  validates :kingdom, presence: true

  has_many :genera, dependent: :restrict_with_exception

  has_paper_trail

  before_validation :normalize_fields

  scope :syncable_with, ->(trusted_family) { Family.where(sync_id: trusted_family[:id].to_s).or(Family.where('lower(name) = ?', trusted_family[:name].downcase)) }

  def normalize_fields
    name&.strip!
    source&.strip!
  end

  class << self
    def normalize_fields
      all.find_each(&:save)
    end
  end
end

app/controllers/admin/families_controller.rb
module Admin
  class FamiliesController < AdminApplicationController
    before_action :set_family, only: [:show, :edit, :update, :destroy]

    # GET /admin/families
    def index
      @families = policy_scope(Family)
      @families = filter @families

      @families = search_order_and_paginate @families, search_fields: ['name'], allowed_sort_fields: ['families.name'], default_sort_field: 'families.name', default_sort_dir: 'asc'
    end

    # GET /admin/families/1
    def show; end

    # GET /admin/families/new
    def new
      authorize Family

      @family = Family.new
    end

    # GET /admin/families/1/edit
    def edit; end

    # POST /admin/families
    def create
      authorize Family

      @family = Family.new(family_params)

      if @family.save
        redirect_to admin_family_path(@family), notice: I18n.t('admin.families.create.success')
      else
        render :new
      end
    end

    # PATCH/PUT /admin/families/1
    def update
      if @family.update(family_params)
        redirect_to admin_family_path(@family), notice: I18n.t('admin.families.update.success')
      else
        render :edit
      end
    end

    # DELETE /admin/families/1
    def destroy
      @family.destroy
      redirect_to admin_families_url, notice: I18n.t('admin.families.destroy.success')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])

      authorize @family
    end

    # Only pick allowed parameters from request
    def family_params
      params.require(:family).permit(:name, :kingdom, :description, :source, :sync_id)
    end

    def filter(query) # rubocop:disable Metrics/MethodLength
      case params[:source]
      when 'with'
        query = query.where.not(source: '')
      when 'without'
        query = query.where(source: '')
      end

      case params[:kingdom]
      when 'animal'
        query = query.where(kingdom: :animal)
      when 'plant'
        query = query.where(kingdom: :plant)
      end

      case params[:genera]
      when 'without'
        query = query.where.missing(:genera)
      end

      query
    end
  end
end

app/controllers/api/families_controller.rb
module Api
  class FamiliesController < ApiApplicationController
    before_action :set_family, only: [:show, :update, :destroy]

    # GET /api/families
    def index
      @families = policy_scope Family

      render 'api/families/index'
    end

    # GET /api/families/1
    def show
      render 'api/families/show'
    end

    # POST /api/families
    def create
      @family = Family.new(family_params)
      authorize @family

      if @family.save
        render 'api/families/show', status: :created, location: api_family_url(@family)
      else
        render json: @family.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /api/families/1
    def update
      if @family.update(family_params)
        render 'api/families/show', status: :ok, location: api_family_url(@family)
      else
        render json: @family.errors, status: :unprocessable_entity
      end
    end

    # DELETE /api/families/1
    def destroy
      @family.destroy
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])

      authorize @family
    end

    # Only pick allowed parameters from request
    def family_params
      base_params = :name, :kingdom, :source
      base_params.push :sync_id if current_user&.admin?

      params.fetch(:family, {}).permit(base_params)
    end
  end
end

app/views/admin/families/_form.html.haml
- url = family.id ? admin_family_path : admin_families_path
= form_for family, url: url do |f|
  - if family.errors.any?
    .gp-alert.gp-alert--danger
      %p= t('.errors', count: family.errors.count)
      %ul
        - family.errors.full_messages.each do |message|
          %li= message

  ._show-page
    %section._show-page__panel
      .gp-field
        = f.label :name
        = f.text_field :name, required: true
      .gp-field
        = f.label :kingdom
        = f.select :kingdom, enum_options_for_select(Family, :kingdom)
      .gp-field
        = f.label :source
        = f.url_field :source

  .gp-actions.gp-actions--bottom
    = f.submit t('generic.save'), class: 'gp-button gp-button--recording'

app/views/admin/families/edit.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), :admin_families, role: 'button', class: 'gp-button'
  = link_to t('generic.show'), admin_family_path(@family), role: 'button', class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_family_path(@family),
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'

= render 'form', family: @family

app/views/admin/families/index.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('.new'), new_admin_family_path, role: 'button', class: 'gp-button gp-button--creative'

- if @families.size.positive?
  = render 'admin/widgets/pagination', list: @families

._filters
  ._filters__section
    ._filters__section__title= t('activerecord.attributes.family.kingdom')
    = filter_by_link t('generic.all'), filters: { kingdom: nil }, keep: [:search, :source, :genera]
    = filter_by_link t('.kingdom.plant'), filters: { kingdom: 'plant' }, keep: [:search, :source, :genera]
    = filter_by_link t('.kingdom.animal'), filters: { kingdom: 'animal' }, keep: [:search, :source, :genera]
  ._filters__section
    ._filters__section__title= t('activerecord.attributes.family.source')
    = filter_by_link t('generic.all'), filters: { source: nil }, keep: [:search, :kingdom, :genera]
    = filter_by_link t('generic.with'), filters: { source: 'with' }, keep: [:search, :kingdom, :genera]
    = filter_by_link t('generic.without'), filters: { source: 'without' }, keep: [:search, :kingdom, :genera]
  ._filters__section
    ._filters__section__title= t('activerecord.models.genus', count: 2)
    = filter_by_link t('generic.all'), filters: { genera: nil }, keep: [:search, :kingdom, :source]
    = filter_by_link t('generic.without'), filters: { genera: 'without' }, keep: [:search, :kingdom, :source]
  ._filters__spring
  ._filters__section= render 'admin/widgets/search', keep: [:kingdom, :source, :genera]

- if @families.empty?
  .gp-empty= t('.no_content')
- else

  %table
    %caption.-sr-only= t('.table_caption')
    %thead
      %tr
        %th.-monospace.-right{ scope: 'col' }= t('generic.id')
        %th.-monospace.-right{ scope: 'col' }= t('activerecord.attributes.family.sync_id')
        %th{ scope: 'col' }= order_by_link t('activerecord.attributes.family.name'),
                                            'families.name',
                                            keep_filters: [:search, :kingdom, :source, :genera]
        %th{ scope: 'col' }= t('activerecord.attributes.family.kingdom')
        %th{ scope: 'col' }= t('activerecord.attributes.family.source')
        %th{ scope: 'col' }= t('activerecord.models.genus', count: 2)
        %th{ scope: 'col' }

    %tbody
      - @families.each do |family|
        %tr
          %td.-monospace.-right= family.id
          %td.-monospace.-right= family.sync_id.presence || '-'
          %td= link_to family.name, admin_family_path(family)
          %td= family.kingdom
          %td.centered{ class: (family.source.present? ? '' : 'warning') }
            = yes_no family.source.present?
          %td.centered= family.genera.size
          %td.-actions
            = link_to t('generic.edit'),
                      edit_admin_family_path(family),
                      role: 'button',
                      class: 'gp-button gp-button--small'
            = link_to t('generic.destroy'),
                      admin_family_path(family),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'gp-button gp-button--small gp-button--destructive'

  = render 'admin/widgets/pagination', list: @families, name: 'family'

app/views/admin/families/new.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_families_path, role: 'button', class: 'gp-button'

= render 'form', family: @family

app/views/admin/families/show.html.haml
- @page_title = t('.title', name: @family.name)

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_families_path, role: 'button', class: 'gp-button'
  = link_to t('generic.edit'), edit_admin_family_path(@family), role: 'button', class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_family_path,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'

._show-page
  %aside._show-page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('generic.id'))
        %dd.-monospace= @family.id

        %dt= t('generic.definition', value: t('activerecord.attributes.family.name'))
        %dd= @family.name

        %dt= t('generic.definition', value: t('activerecord.attributes.family.sync_id'))
        %dd= @family.sync_id.presence || '-'

        %dt= t('generic.definition', value: t('activerecord.attributes.family.kingdom'))
        %dd= @family.kingdom

        %dt= t('generic.definition', value: t('activerecord.attributes.family.source'))
        = missing_data_element :dd, @family.source.present?, url: edit_admin_family_path(@family) do
          - link_to @family.source, @family.source, rel: 'noreferrer noopener'

  ._show-page__content.-grid--2.-grid-gap
    %section
      %h2= t('.genera')
      - if @family.genera.empty?
        .gp-empty= t('generic.nothing_to_display_yet')
      - else
        %table
          %thead
            %tr
              %th= t('activerecord.attributes.genus.name')
              %th
          %tbody
            - @family.genera.each do |genus|
              %tr
                %td= link_to genus.name, admin_genus_url(genus)
                %td.-actions
                  = link_to t('generic.edit'), edit_admin_genus_path(genus),
                            role: 'button',
                            class: 'gp-button'
                  = link_to t('generic.destroy'),
                            admin_genus_path(genus),
                            method: :delete,
                            data: { confirm: t('generic.are_you_sure') },
                            role: 'button',
                            class: 'gp-button gp-button--destructive'
      .gp-actions
        = link_to t('.new_genus'),
                  new_admin_genus_path(params: { family_id: @family.id }),
                  class: 'gp-button gp-button--creative'
    %section= render 'admin/versions/versions', entity: @family