config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users, skip: :invitations

  devise_scope :user do
    # Disable every invitation routes except "/accept", we're managing these in the API
    get 'users/invitations/accept', to: 'devise/invitations#edit', as: :accept_user_invitation
    put 'users/invitations', to: 'devise/invitations#update', as: :user_invitation
  end

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/app/*path', to: 'app#app'
  get '/shared/maps/:map_id', to: 'app#shared', as: :shared_map
  get '/changelog', to: 'app#changelog'

  # Tools
  get '/tools', to: 'tools#index'
  get '/tools/soil-analysis', to: 'tools#soil_analysis'

  resources :links, except: [:show]

  namespace :api do
    api_routes_exceptions = [:new, :edit]
    no_index_api_routes_exceptions = [:index, :new, :edit]

    with_options except: api_routes_exceptions do |api_route|
      # Community-related endpoints
      api_route.resources :families
      api_route.resources :genera
      api_route.resources :resource_interactions
      api_route.resources :resource_interactions_groups
      api_route.resources :resource_notes, except: [:index]
      api_route.resources :resources do
        api_route.resources :resource_notes, only: [:index], path: 'notes'
      end

      # User-related endpoints
      api_route.resource :account, only: [:show, :update]

      # Map-related endpoint, for updates and display
      api_route.resources :activities, only: [:show]
      api_route.resources :elements, except: no_index_api_routes_exceptions do
        api_route.resources :harvests, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
        member do
          post '/duplicate', to: 'elements#duplicate'
        end
      end
      api_route.resources :harvests, except: no_index_api_routes_exceptions
      api_route.resources :layers, except: no_index_api_routes_exceptions
      api_route.resources :notifications, only: [:index, :show, :destroy] do
        collection do
          patch '/archive_all', to: 'notifications#archive_all', as: :archive_all
          delete '/destroy_all_archived', to: 'notifications#destroy_all_archived', as: :destroy_all_archived
        end
        patch '/archive', to: 'notifications#archive', on: :member, as: :archive
      end
      api_route.resources :observations, except: no_index_api_routes_exceptions do
        get '/pictures/:picture_id', to: 'observations#picture', on: :member, as: :picture
        get '/pictures/:picture_id/thumbnail', to: 'observations#picture_thumbnail', on: :member, as: :picture_thumbnail
      end
      api_route.resources :patches, except: no_index_api_routes_exceptions do
        api_route.resources :elements, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :paths, except: no_index_api_routes_exceptions do
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :tasks, except: no_index_api_routes_exceptions
      api_route.resources :team_mates, only: [:create, :show] do
        member do
          patch '/accept', to: 'team_mates#accept'
          delete '/refuse', to: 'team_mates#refuse'
          delete '/leave', to: 'team_mates#leave'
          delete '/remove', to: 'team_mates#remove'
        end
      end
      api_route.resources :users, only: [:show] do
        collection do
          post '/search', to: 'users#search'
          post '/invite', to: 'users#invite'
        end
        post '/resend_invitation', to: 'users#resend_invitation', on: :member
      end

      # Maps and their own data, for listings
      api_route.resources :maps do
        get :picture, on: :member
        # Observations directly linked to the map
        api_route.resources :observations, only: [:index]
        api_route.resources :elements, only: [:index]
        api_route.resources :layers, only: [:index]
        api_route.resources :patches, only: [:index]
        api_route.resources :paths, only: [:index]
        api_route.resources :tasks, only: [:index] do
          get '/names', to: 'tasks#names', on: :collection
        end
        api_route.resources :team_mates, only: [:index]
        # Activities for anything linked to the map
        get '/all_activities', to: 'activities#index', as: :all_activities
        # Harvests for anything linked to the map
        get '/all_harvests', to: 'harvests#all_for_map', as: :all_harvests
        # Observations for anything linked to the map
        get '/all_observations', to: 'observations#all_for_map', as: :all_observations
        # Tasks for anything linked to the map
        get '/all_tasks', to: 'tasks#all_for_map', as: :all_tasks
      end
      get 'shared/maps/:id', to: 'maps#shared', as: :shared_map
    end
  end

  namespace :admin do
    resources :families, concerns: :paginatable
    resources :genera, concerns: :paginatable
    resources :resource_interactions_groups, concerns: :paginatable
    resources :resource_interactions, concerns: :paginatable
    resources :resource_notes, only: [:destroy]
    resources :resources, concerns: :paginatable
    resources :links, except: [:show] do
      put :approve, on: :member
    end
    resources :tags, except: [:new] do
      collection do
        post :batch_process
      end
    end

    get '/import', to: 'import#index'
    get '/import/differences', to: 'import#differences'
    get '/import/library_names', to: 'import#library_names'

    %w[family genus resource resource_interactions_group resource_interaction].each do |r|
      post "/import/#{r}", controller: :import, action: r
      put "/import/#{r}", controller: :import, action: r
    end
  end
end

app/controllers/admin/resource_interactions_controller.rb
module Admin
  class ResourceInteractionsController < AdminApplicationController
    before_action :set_resource_interaction, only: [:show, :edit, :update, :destroy]

    # GET /admin/resource_interactions
    def index
      @resource_interactions = policy_scope ResourceInteraction.all
    end

    # GET /admin/resource_interactions/1
    def show; end

    # GET /admin/resource_interactions/new
    def new
      authorize ResourceInteraction

      @resource_interaction = ResourceInteraction.new
    end

    # GET /admin/resource_interactions/1/edit
    def edit; end

    # POST /admin/resource_interactions
    def create
      authorize ResourceInteraction

      @resource_interaction = ResourceInteraction.new(resource_interaction_params)

      if @resource_interaction.save
        redirect_to admin_resource_interaction_path(@resource_interaction), notice: I18n.t('admin.resource_interactions.create.success')
      else
        render :new
      end
    end

    # PATCH/PUT /admin/resource_interactions/1
    def update
      if @resource_interaction.update(resource_interaction_params)
        redirect_to admin_resource_interaction_path(@resource_interaction), notice: I18n.t('admin.resource_interactions.update.success')
      else
        render :edit
      end
    end

    # DELETE /admin/resource_interactions/1
    def destroy
      @resource_interaction.destroy
      redirect_to admin_resource_interactions_url, notice: I18n.t('admin.resource_interactions.destroy.success')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource_interaction
      @resource_interaction = ResourceInteraction.find(params[:id])

      authorize @resource_interaction
    end

    # Only pick allowed parameters from request
    def resource_interaction_params
      params.require(:resource_interaction).permit(:nature, :notes, :sources, :subject_id, :target_id, :sync_id)
    end
  end
end

app/controllers/api/resource_interactions_controller.rb
module Api
  class ResourceInteractionsController < ApiApplicationController
    before_action :set_resource_interaction, only: [:show, :update, :destroy]

    # GET /resource_interactions
    def index
      @resource_interactions = policy_scope ResourceInteraction

      render 'api/resource_interactions/index'
    end

    # GET /resource_interactions/1
    def show
      render 'api/resource_interactions/show'
    end

    # POST /resource_interactions
    def create
      authorize ResourceInteraction
      @resource_interaction = ResourceInteraction.new(resource_interaction_params)

      if @resource_interaction.save
        render 'api/resource_interactions/show', status: :created, location: api_resource_interaction_url(@resource_interaction)
      else
        render json: @resource_interaction.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /resource_interactions/1
    def update
      if @resource_interaction.update(resource_interaction_params)
        render 'api/resource_interactions/show', status: :ok, location: api_resource_interaction_url(@resource_interaction)
      else
        render json: @resource_interaction.errors, status: :unprocessable_entity
      end
    end

    # DELETE /resource_interactions/1
    def destroy
      @resource_interaction.destroy
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource_interaction
      @resource_interaction = ResourceInteraction.find(params[:id])

      authorize @resource_interaction
    end

    # Only pick allowed parameters from request
    def resource_interaction_params
      base_params = :subject_id, :target_id, :nature, :notes, :sources
      base_params.push :sync_id if current_user&.admin?

      params.require(:resource_interaction).permit(base_params)
    end
  end
end

app/views/admin/resource_interactions/_form.html.haml
- url = resource_interaction.id ? admin_resource_interaction_path : admin_resource_interactions_path
= form_for resource_interaction, url: url do |f|
  - if resource_interaction.errors.any?
    .gp-alert.gp-alert--danger
      %p= t('.errors', count: resource_interaction.errors.count)
      %ul
        - resource_interaction.errors.full_messages.each do |message|
          %li= message

  ._show-page
    %section._show-page__panel
      .gp-field
        = f.label :subject_id, t('activerecord.attributes.resource_interaction.subject')
        = f.collection_select :subject_id,
                              ResourceInteractionsGroup.all.order(:name),
                              :id,
                              :name,
                              { include_blank: true },
                              { required: true }
      .gp-field
        = f.label :nature
        = f.select :nature,
                   enum_options_for_select(ResourceInteraction, :nature),
                   { include_blank: true },
                   { required: true }
      .gp-field
        = f.label :target_id, t('activerecord.attributes.resource_interaction.target')
        = f.collection_select :target_id,
                              ResourceInteractionsGroup.all.order(:name),
                              :id,
                              :name,
                              { include_blank: true },
                              { required: true }

      .gp-field
        = f.label :notes
        = f.text_field :notes

      .gp-field
        = f.label :sources
        = f.text_area :sources
        .gp-field__help= t('.sources_help')

    ._show-page__content
      = render 'admin/resource_interactions/form_help'

  .gp-actions.gp-actions--bottom
    = f.submit t('generic.save'), class: 'gp-button gp-button--recording'

app/views/admin/resource_interactions/_form_help.html.haml
%aside.gp-alert
  = t('.more_info_link_html', url: t('.wikipedia_url'))

%table
  %thead
    %tr{ scope: :column }
      %th= t('activerecord.attributes.resource_interaction.nature')
      %th.-center= t('activerecord.attributes.resource_interaction.subject')
      %th.-center= t('activerecord.attributes.resource_interaction.target')
      %th= t('.description')
  %tbody
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.unspecified_positive')
      %td.-center ?
      %td.-center ?
      %td= t('models.resource_interaction.natures.unspecified_positive_help')
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.unspecified_negative')
      %td.-center ?
      %td.-center ?
      %td= t('models.resource_interaction.natures.unspecified_negative_help')
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.mutualism')
      %td.-center.-text--success= icon('smiley')
      %td.-center.-text--success= icon('smiley')
      %td= t('models.resource_interaction.natures.mutualism_help')
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.commensalism')
      %td.-center.-text--success= icon('smiley')
      %td.-center.-text--mute= icon('smiley-meh')
      %td= t('models.resource_interaction.natures.commensalism_help')
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.parasitism')
      %td.-center.-text--success= icon('smiley')
      %td.-center.-text--danger= icon('smiley-sad')
      %td= t('models.resource_interaction.natures.parasitism_help')
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.neutralism')
      %td.-center.-text--mute= icon('smiley-meh')
      %td.-center.-text--mute= icon('smiley-meh')
      %td= t('models.resource_interaction.natures.neutralism_help')
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.amensalism')
      %td.-center.-text--mute= icon('smiley-meh')
      %td.-center.-text--danger= icon('smiley-sad')
      %td= t('models.resource_interaction.natures.amensalism_help')
    %tr
      %td= t('activerecord.attributes.resource_interaction/nature.competition')
      %td.-center.-text--danger= icon('smiley-sad')
      %td.-center.-text--danger= icon('smiley-sad')
      %td= t('models.resource_interaction.natures.competition_help')

app/views/admin/resource_interactions/edit.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), :admin_resource_interactions, role: 'button', class: 'gp-button'
  = link_to t('generic.show'),
            admin_resource_interaction_path(@resource_interaction),
            role: 'button',
            class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_resource_interaction_path(@resource_interaction),
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'

= render 'form', resource_interaction: @resource_interaction

app/views/admin/resource_interactions/index.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('.new'),
            new_admin_resource_interaction_path,
            role: 'button',
            class: 'gp-button gp-button--creative'

- if @resource_interactions.empty?
  .gp-empty= t('.no_content')
- else
  %table
    %caption.-sr-only= t('.table_caption')
    %thead
      %tr
        %th.-monospace.-right{ scope: 'col' }= t('generic.id')
        %th.-monospace.-right{ scope: 'col' }= t('activerecord.attributes.genus.sync_id')
        %th{ scope: 'col' }= t('activerecord.attributes.resource_interaction.subject')
        %th{ scope: 'col' }= t('activerecord.attributes.resource_interaction.nature')
        %th{ scope: 'col' }= t('activerecord.attributes.resource_interaction.target')
        %th{ scope: 'col' }= t('activerecord.attributes.resource_interaction.notes')
        %th{ scope: 'col' }

    %tbody
      - @resource_interactions.each do |resource_interaction|
        %tr
          %td.-monospace.-right= resource_interaction.id
          %td.-monospace.-right= resource_interaction.sync_id.presence || '-'
          %td= resource_interaction.subject.name
          %td
            &rarr;
            = link_to resource_interaction.nature, admin_resource_interaction_path(resource_interaction)
            &rarr;
          %td= resource_interaction.target.name
          %td= resource_interaction.notes
          %td.-actions
            = link_to t('generic.edit'),
                      edit_admin_resource_interaction_path(resource_interaction),
                      role: 'button',
                      class: 'gp-button gp-button--small'
            = link_to t('generic.destroy'),
                      admin_resource_interaction_path(resource_interaction),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'gp-button gp-button--small gp-button--destructive'

app/views/admin/resource_interactions/new.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_resource_interactions_path, role: 'button', class: 'gp-button'

= render 'form', resource_interaction: @resource_interaction

app/views/admin/resource_interactions/show.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_resource_interactions_path, role: 'button', class: 'gp-button'
  = link_to t('generic.edit'),
            edit_admin_resource_interaction_path(@resource_interaction),
            role: 'button',
            class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_resource_interaction_path,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'
._show-page
  %aside._show-page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('generic.id'))
        %dd.-monospace= @resource_interaction.id

        %dt= t('generic.definition', value: t('activerecord.attributes.resource_interaction.subject'))
        %dd= @resource_interaction.subject.name

        %dt= t('generic.definition', value: t('activerecord.attributes.resource_interaction.nature'))
        %dd= @resource_interaction.nature

        %dt= t('generic.definition', value: t('activerecord.attributes.resource_interaction.target'))
        %dd= @resource_interaction.target.name

  ._show-page__content
    %h2= t('activerecord.attributes.resource_interaction.notes')
    = @resource_interaction.notes