config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users, skip: :invitations

  devise_scope :user do
    # Disable every invitation routes except "/accept", we're managing these in the API
    get 'users/invitations/accept', to: 'devise/invitations#edit', as: :accept_user_invitation
    put 'users/invitations', to: 'devise/invitations#update', as: :user_invitation
  end

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/app/*path', to: 'app#app'
  get '/shared/maps/:map_id', to: 'app#shared', as: :shared_map
  get '/changelog', to: 'app#changelog'

  # Tools
  get '/tools', to: 'tools#index'
  get '/tools/soil-analysis', to: 'tools#soil_analysis'

  resources :links, except: [:show]

  namespace :api do
    api_routes_exceptions = [:new, :edit]
    no_index_api_routes_exceptions = [:index, :new, :edit]

    with_options except: api_routes_exceptions do |api_route|
      # Community-related endpoints
      api_route.resources :families
      api_route.resources :genera
      api_route.resources :resource_interactions
      api_route.resources :resource_interactions_groups
      api_route.resources :resource_notes, except: [:index]
      api_route.resources :resources do
        api_route.resources :resource_notes, only: [:index], path: 'notes'
      end

      # User-related endpoints
      api_route.resource :account, only: [:show, :update]

      # Map-related endpoint, for updates and display
      api_route.resources :activities, only: [:show]
      api_route.resources :elements, except: no_index_api_routes_exceptions do
        api_route.resources :harvests, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
        member do
          post '/duplicate', to: 'elements#duplicate'
        end
      end
      api_route.resources :harvests, except: no_index_api_routes_exceptions
      api_route.resources :layers, except: no_index_api_routes_exceptions
      api_route.resources :notifications, only: [:index, :show, :destroy] do
        collection do
          patch '/archive_all', to: 'notifications#archive_all', as: :archive_all
          delete '/destroy_all_archived', to: 'notifications#destroy_all_archived', as: :destroy_all_archived
        end
        patch '/archive', to: 'notifications#archive', on: :member, as: :archive
      end
      api_route.resources :observations, except: no_index_api_routes_exceptions do
        get '/pictures/:picture_id', to: 'observations#picture', on: :member, as: :picture
        get '/pictures/:picture_id/thumbnail', to: 'observations#picture_thumbnail', on: :member, as: :picture_thumbnail
      end
      api_route.resources :patches, except: no_index_api_routes_exceptions do
        api_route.resources :elements, only: [:index]
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :paths, except: no_index_api_routes_exceptions do
        api_route.resources :observations, only: [:index]
        api_route.resources :tasks, only: [:index]
      end
      api_route.resources :tasks, except: no_index_api_routes_exceptions
      api_route.resources :team_mates, only: [:create, :show] do
        member do
          patch '/accept', to: 'team_mates#accept'
          delete '/refuse', to: 'team_mates#refuse'
          delete '/leave', to: 'team_mates#leave'
          delete '/remove', to: 'team_mates#remove'
        end
      end
      api_route.resources :users, only: [:show] do
        collection do
          post '/search', to: 'users#search'
          post '/invite', to: 'users#invite'
        end
        post '/resend_invitation', to: 'users#resend_invitation', on: :member
      end

      # Maps and their own data, for listings
      api_route.resources :maps do
        get :picture, on: :member
        # Observations directly linked to the map
        api_route.resources :observations, only: [:index]
        api_route.resources :elements, only: [:index]
        api_route.resources :layers, only: [:index]
        api_route.resources :patches, only: [:index]
        api_route.resources :paths, only: [:index]
        api_route.resources :tasks, only: [:index] do
          get '/names', to: 'tasks#names', on: :collection
        end
        api_route.resources :team_mates, only: [:index]
        # Activities for anything linked to the map
        get '/all_activities', to: 'activities#index', as: :all_activities
        # Harvests for anything linked to the map
        get '/all_harvests', to: 'harvests#all_for_map', as: :all_harvests
        # Observations for anything linked to the map
        get '/all_observations', to: 'observations#all_for_map', as: :all_observations
        # Tasks for anything linked to the map
        get '/all_tasks', to: 'tasks#all_for_map', as: :all_tasks
      end
      get 'shared/maps/:id', to: 'maps#shared', as: :shared_map
    end
  end

  namespace :admin do
    resources :families, concerns: :paginatable
    resources :genera, concerns: :paginatable
    resources :resource_interactions_groups, concerns: :paginatable
    resources :resource_interactions, concerns: :paginatable
    resources :resource_notes, only: [:destroy]
    resources :resources, concerns: :paginatable
    resources :links, except: [:show] do
      put :approve, on: :member
    end
    resources :tags, except: [:new] do
      collection do
        post :batch_process
      end
    end

    get '/import', to: 'import#index'
    get '/import/differences', to: 'import#differences'
    get '/import/library_names', to: 'import#library_names'

    %w[family genus resource resource_interactions_group resource_interaction].each do |r|
      post "/import/#{r}", controller: :import, action: r
      put "/import/#{r}", controller: :import, action: r
    end
  end
end

app/views/admin/resources/_form.html.haml
= vite_javascript_tag 'vue-tag-selector'

- url = resource.id ? admin_resource_path : admin_resources_path
= form_for resource, url: url do |f|
  - if resource.errors.any?
    .gp-alert.gp-alert--danger
      %p= t('.errors', count: resource.errors.count)
      %ul
        - resource.errors.full_messages.each do |message|
          %li= message

  ._show-page
    %section._show-page__panel
      .gp-field
        = f.label :name
        = f.text_field :name, required: true
      .gp-field
        = f.label :latin_name
        = f.text_field :latin_name, required: true
      .gp-field
        = f.label :resource_interactions_group
        = f.collection_select :resource_interactions_group_id,
                              ResourceInteractionsGroup.order(:name),
                              :id,
                              :name,
                              prompt: true
        .gp-field__help= t('.resource_interactions_group_help')
      .gp-field
        = f.label :tag_list
        = tag_selector f, :tag_list, :resource_tag_list, resource.tag_list
      .gp-field
        = f.label :diameter
        = f.number_field :diameter, step: 0.01, min: 0
      .gp-field
        = f.label :color do
          = t('activerecord.attributes.resource.color')
          .color_preview#color-preview
        = f.text_field :color, required: true
        .gp-field__help= t('.color_help')
      .gp-field
        = f.label :common_names
        = f.text_field :common_names, value: resource.common_names.join(', ')
        .gp-field__help= t('generic.comma_separated_values')
      .gp-field
        = f.label :sources
        = f.text_area :sources, value: resource.sources.join("\n")
        .gp-field__help= t('.sources_help')
      .gp-field
        = f.label :parent_id, t('activerecord.attributes.resource.parent')
        = f.collection_select :parent_id, Resource.parentable.order(:name), :id, :name, prompt: true
      .gp-field
        = f.label :genus_id, t('activerecord.attributes.resource.genus')
        = f.collection_select :genus_id, Genus.all.order(:name), :id, :name, { include_blank: true }, required: true
    %section._show-page__content
      .gp-field
        = f.label :description
        = f.text_area :description, class: '-markdown -large'

      - Resource::BITFIELD_MONTHS_ATTRIBUTES.each_pair do |field, prefix|
        .gp-field
          %label= t("activerecord.attributes.resource.#{field}")
          .gp-month-flags-input
            - fields = GardenParty::BitfieldModelHelper.bitfield_months(prefix)
            - fields.each_pair do |key, attribute|
              = f.label attribute do
                = f.check_box attribute
                = t('date.abbr_month_names')[fields.keys.find_index(key) + 1]

  .gp-actions.gp-actions--bottom
    = f.submit t('generic.save'), class: 'gp-button gp-button--recording'

:javascript
  function updateColorPreview() {
    var target = document.getElementById('color-preview')
    var input  = document.getElementById('resource_color')
    var valid = true
    input.value.split(',').map(function(c) {return c.trim()}).forEach(function(e) {
      var value = parseInt(e, 10)
      if(!/^\d{1,3}$/.test(e) || value > 255 || value < 0) valid = false
    })
    if(valid) {
      target.style.backgroundColor= 'rgb('+input.value+')'
      input.setCustomValidity('');
    } else {
      input.setCustomValidity('#{escape_javascript(t('activerecord.errors.bad_color_segment'))}');
    }
  }
  document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('resource_color').addEventListener('input', updateColorPreview)
    updateColorPreview()
  })

app/views/admin/resources/edit.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), :admin_resources, role: 'button', class: 'gp-button'
  = link_to t('generic.show'), admin_resource_path(@resource), role: 'button', class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_resource_path(@resource),
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'

= render 'form', resource: @resource

app/views/admin/resources/index.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('.new'), new_admin_resource_path, role: 'button', class: 'gp-button gp-button--creative'

- if @resources.size.positive?
  = render 'admin/widgets/pagination', list: @resources

._filters
  ._filters__section
    ._filters__section__title= t('.usage')
    = filter_by_link t('generic.all'), filters: { elements: nil }, keep: [:search, :source]
    = filter_by_link t('.unused'), filters: { elements: 'without' }, keep: [:search, :source]
  ._filters__spring
  ._filters__section= render 'admin/widgets/search', keep: [:source, :elements]

- if @resources.empty?
  .gp-empty= t('.no_content')
- else
  %table
    %caption.-sr-only= t('.table_caption')
    %thead
      %tr
        %th.-monospace.-right{ scope: 'col' }= t('generic.id')
        %th.-monospace.-right{ scope: 'col' }= t('activerecord.attributes.resource.sync_id')
        %th{ scope: 'col' }= order_by_link t('activerecord.attributes.resource.name'),
                                          'name',
                                          keep_filters: [:search, :source, :elements]
        %th{ scope: 'col' }= order_by_link t('activerecord.attributes.resource.latin_name'),
                                          'latin_name',
                                          keep_filters: [:search, :source, :elements]
        %th{ scope: 'col' }= t('activerecord.attributes.resource.diameter')
        %th{ scope: 'col' }= t('activerecord.attributes.resource.parent')
        %th{ scope: 'col' }= t('activerecord.attributes.resource.genus')
        %th{ scope: 'col' }= t('activerecord.attributes.resource.sources')
        %th{ scope: 'col' }= t('activerecord.models.element', count: 2)
        %th{ scope: 'col' }

    %tbody
      - @resources.each do |resource|
        %tr
          %td.-monospace.-right= resource.id
          %td.-monospace.-right= resource.sync_id.presence || '-'
          %td{ class: resource.generic? ? '-italic' : '' }= link_to resource.name, admin_resource_path(resource)
          = missing_data_element :td, resource.latin_name, replacement: '-'
          = missing_data_element :td, resource.diameter, replacement: '-'
          %td
            - if resource.parent.present?
              = link_to resource.parent.name, admin_resource_path(resource.parent)
            - else
              \-
          %td= resource.genus.name
          %td.centered{ class: (resource.sources.length.positive? ? '' : '-text--warning') }
            = yes_no resource.sources.length.positive?
          %td.centered= resource.elements.size
          %td.-actions
            = link_to t('generic.edit'),
                      edit_admin_resource_path(resource),
                      role: 'button',
                      class: 'gp-button gp-button--small'
            = link_to t('generic.destroy'),
                      admin_resource_path(resource),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'gp-button gp-button--small gp-button--destructive'

  = render 'admin/widgets/pagination', list: @resources, name: 'resource'

app/views/admin/resources/new.html.haml
- @page_title = t('.title')

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_resources_path, role: 'button', class: 'gp-button'

= render 'form', resource: @resource

app/views/admin/resources/show.html.haml
-# haml-lint:disable ViewLength
- @page_title = t('.title', name: @resource.name)

.gp-actions.gp-actions--top
  = link_to t('generic.back'), admin_resources_path, role: 'button', class: 'gp-button'
  = link_to t('generic.edit'), edit_admin_resource_path(@resource), role: 'button', class: 'gp-button'
  = link_to t('generic.destroy'),
            admin_resource_path,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button',
            class: 'gp-button gp-button--destructive'
._show-page
  %aside._show-page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('generic.id'))
        %dd.-monospace= @resource.id

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.generic'))
        %dd= yes_no @resource.generic?

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.latin_name'))
        = missing_data_element :dd, @resource.latin_name, url: edit_admin_resource_path(@resource)

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.sync_id'))
        %dd= @resource.sync_id.presence || '-'

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.genus'))
        %dd= link_to @resource.genus.name, admin_genus_path(@resource.genus)

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.resource_interactions_group'))
        -# haml-lint:disable LineLength
        %dd= @resource.resource_interactions_group ? link_to(@resource.resource_interactions_group.name, admin_resource_interactions_group_path(@resource.resource_interactions_group)) : '-'
        -# haml-lint:enable LineLength

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.sources'))
        %dd
          - missing_data_element :dd, @resource.sources.length.positive?, url: edit_admin_resource_path(@resource) do
            %ul
              - @resource.sources.each do |source|
                %li= link_to source, source

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.common_names'))
        %dd
          - if @resource.common_names.empty?
            \-
          - else
            %ul
              - @resource.common_names.each do |cn|
                %li= cn

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.diameter'))
        = missing_data_element :dd, @resource.diameter, replacement: '-'

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.parent'))
        %dd= @resource.parent ? @resource.parent.name : '-'

        %dt= t('generic.definition', value: t('activerecord.models.element', count: 2))
        %dd= @resource.elements.size

        %dt= t('generic.definition', value: t('activerecord.models.tag_list', count: 2))
        %dd.tags
          - @resource.tag_list.each do |tag|
            = compound_tag tag

  ._show-page__content.-grid--2.-grid-gap
    %div
      %section
        %h2= t('activerecord.attributes.resource.description')
        #markdown
          #markdown-source= @resource.description

      %section
        %h2= t('js.resources.description_area.sow_harvest')
        %table.auto-width.small
          %thead
            %tr
              - t('date.abbr_month_names').each do |month|
                %th= month
          %tbody
            %tr.right-aligned
              %th= t('js.resources.description_area.sheltered_sowing_months')
              - values = Resource.bitfield_month_to_a @resource.bitfield_values(:sheltered_sowing_months),
                                                      :sow_sheltered_in
              - values.each do |value|
                %td{ class: value ? '-ok' : '' }
            %tr.right-aligned
              %th= t('js.resources.description_area.soil_sowing_months')
              - values = Resource.bitfield_month_to_a @resource.bitfield_values(:soil_sowing_months),
                                                      :sow_in_soil_in
              - values.each do |value|
                %td{ class: value ? '-ok' : '' }
            %tr.right-aligned
              %th= t('js.resources.description_area.harvesting_months')
              - values = Resource.bitfield_month_to_a @resource.bitfield_values(:harvesting_months),
                                                      :harvest_in
              - values.each do |value|
                %td{ class: value ? '-ok' : '' }

      - if @resource.parent.blank?
        %section
          %h2= t('.variants')
          - if @resource.children.empty?
            .gp-alert.gp-alert--mute= t('.no_child_resource')
          - else
            %ul
              - @resource.children.order(:name).each do |resource|
                %li= link_to resource.name, admin_resource_path(resource)

    %section= render 'admin/versions/versions', entity: @resource

    %section
      %h2= t('.user_notes')
      - if @resource.notes.count.zero?
        .gp-alert.gp-alert--mute= t('.no_user_note')
      - else
        %table.auto-width.small
          %thead
            %tr
              %th= t 'activerecord.attributes.user.username'
              %th= t 'activerecord.attributes.resource_note.content'
              %th
          %tbody
            - @resource.notes.visible.each do |note|
              %tr
                %td= note.user.username
                %td= note.content
                %td.-actions= link_to t('generic.destroy'),
                              admin_resource_note_path(note),
                              method: :delete,
                              data: { confirm: t('generic.are_you_sure') },
                              role: 'button',
                              class: 'gp-button gp-button--small gp-button--destructive'

:javascript
  document.addEventListener('DOMContentLoaded', () => {
    renderMD(document.getElementById('markdown'), document.getElementById('markdown-source'))
  })
-# haml-lint:enable ViewLength